### ISSUE TITLE
Connect GitHub with BuddyBuild

### ISSUE THREAD

**Issue by rudolf-adamkovic** [enfluid/apple-scrub-bar#18]
CC: @andris-zalitis @ruslankmlv

**Comment by rudolf-adamkovic** [comment]
BuddyBuild configured here:
https://dashboard.buddybuild.com/apps/585be85405e37f01000a9a72

Issue:
<img width="583" alt="screen shot 2016-12-22 at 15 53 53" src="https://cloud.githubusercontent.com/assets/1158274/21429449/108374c4-c85f-11e6-89f5-ad7e064eecc2.png">

**Comment by enfluid** [comment]
Done!
