### ISSUE TITLE
Fix rounded corners and constraints for selection view

### ISSUE THREAD

**Issue by ruslankmlv** [enfluid/apple-scrub-bar#3]

**Comment by ruslankmlv** [comment]
![simulator screen shot nov 1 2016 11 36 27 am](https://cloud.githubusercontent.com/assets/4131355/19902328/899be716-a027-11e6-9bd5-59072881af21.png)

**Comment by ruslankmlv** [comment]
![simulator screen shot nov 1 2016 11 36 27 am](https://cloud.githubusercontent.com/assets/4131355/19902364/b89b4cd2-a027-11e6-8bc7-0b313d5c508d.png)

**Comment by ruslankmlv** [comment]
@salutis For rounded corners, `min(stackView.bounds.width, stackView.bounds.height)` is not the right solution. And to make selection view look like a circle, we need to remove leading/trailing constraints to button and add centerX/centerY constraints to button and width/height constraint of selection view needs to be set to min of buttons height and buttons width

**Comment by rudolf-adamkovic** [comment]
@ruslankmlv Alternatively, we don't make a circle.

**Comment by andris-zalitis** [comment]
Solved with #1
