### ISSUE TITLE
Do not call delegate when selectedIndex is set

### ISSUE THREAD

**Issue by rudolf-adamkovic** [enfluid/apple-scrub-bar#30]
This goes against rules for the delegate pattern in Cocoa.

**Comment by rudolf-adamkovic** [comment]
@andris-zalitis Tried to figure this out but the unit tests are complex — tons of helpers, functions, etc. I think we will save time if you do this. Basically, all we need is to **not** inform delegate when `selectedIndex` property is changed from "outside". This is standard convention in Cocoa.

**Comment by magda-o** [comment]
@andris-zalitis please add a time estimate in Everhour

**Comment by rudolf-adamkovic** [comment]
This was fixed in #31. Closing.
