### ISSUE TITLE
Rename SlidingSegmentedControl to ScrubBar

### ISSUE THREAD

**Issue by andris-zalitis** [enfluid/apple-scrub-bar#8]

**Comment by enfluid** [comment]
@andris-zalitis @salutis Are we sure Scrub Bar is the right name for this control?  To me, a scrub bar is the slider control for changing the playback position of music or video.

**Comment by andris-zalitis** [comment]
We are basing UX on Apple's emoji selection bar. This control will have the same scrubbing interaction when swiping horizontally over it.
Apple calls the view responsible for this UX `UIKeyboardEmojiScrubBarView`. I think word _scrub_ is used here because small horizontal touch movement over the bar results in a large movement for panels above (which is somewhat similar to _scrub_ in a video playback). @enfluid what do you think?

**Comment by enfluid** [comment]
Fair enough.  Sounds like there's a precedent for it.

**Comment by rudolf-adamkovic** [comment]
@andris-zalitis Great explanation!
